<a href="https://colab.research.google.com/github/kumarketanbansal-hue/Python-Pandas/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
x = [1, 2, 3, 4, 5]
s = pd.Series(x, index=["Mon", "Tue", "Wed", "Thu", "Fri"])
print(s)

Mon    1
Tue    2
Wed    3
Thu    4
Fri    5
dtype: int64

In [ ]:
dictionary = {"Mon": 1, "Tue": 2, "Wed": 2, "Thu": 4, "Fri": 5}
s = pd.Series(dictionary)
print(s)

Mon    1
Tue    2
Wed    2
Thu    4
Fri    5
dtype: int64

In [ ]:
dictionary = {"Mon": x, "Tue": x, "Wed": x, "Thu": x, "Fri": x}
s = pd.Series(dictionary, index=["Mon", "Wed", "Thu"]) # Key Selection / Reindexing
print(s)

Mon    [1, 2, 3, 4, 5]
Wed    [1, 2, 3, 4, 5]
Thu    [1, 2, 3, 4, 5]
dtype: object

In [ ]:
s[["Mon", "Thu"]] # Only Index

Mon    [1, 2, 3, 4, 5]
Thu    [1, 2, 3, 4, 5]
dtype: object

In [ ]:
y = [[1, 8, 15, 22], [2, 9, 16, 23], [3, 10, 17, 24], [4, 11, 18, 25], [5, 12, 19, 26]]
df = pd.DataFrame(y, columns=["Week1", "Week2", "Week3", "Week4"], index=["Mon", "Tue", "Wed", "Thu", "Fri"])
print(df)

     Week1  Week2  Week3  Week4
Mon      1      8     15     22
Tue      2      9     16     23
Wed      3     10     17     24
Thu      4     11     18     25
Fri      5     12     19     26

In [ ]:
df['Week1'] # Only Columns

Mon    1
Tue    2
Wed    3
Thu    4
Fri    5
Name: Week1, dtype: int64

In [ ]:
df[["Week1", "Week4"]] # Only Columns

     Week1  Week4
Mon      1     22
Tue      2     23
Wed      3     24
Thu      4     25
Fri      5     26

In [ ]:
y1 = [29, 30, 31, 1, 2]
df["NextMonth"] = y1
print(df)

     Week1  Week2  Week3  Week4  NextMonth
Mon      1      8     15     22         29
Tue      2      9     16     23         30
Wed      3     10     17     24         31
Thu      4     11     18     25          1
Fri      5     12     19     26          2

In [ ]:
df["NewCol"] = 0
print(df)

     Week1  Week2  Week3  Week4  NextMonth  NewCol
Mon      1      8     15     22         29       0
Tue      2      9     16     23         30       0
Wed      3     10     17     24         31       0
Thu      4     11     18     25          1       0
Fri      5     12     19     26          2       0

In [ ]:
del df["NewCol"]
print(df)

     Week1  Week2  Week3  Week4  NextMonth
Mon      1      8     15     22         29
Tue      2      9     16     23         30
Wed      3     10     17     24         31
Thu      4     11     18     25          1
Fri      5     12     19     26          2

In [ ]:
import numpy as np
import random
df1 = pd.DataFrame({'Name':['PUBG: Battlegrounds', 'Tetris (EA)', 'Grand Theft Auto V', 'Wii Sports', 'Minecraft'],
                   'Genre':['Battle royale', 'Puzzle', 'Action-adventure', 'Sports simulation', 'Survival,Sandbox'],
                   'Platform':['PC', 'Multi-platform', 'Multi-platform', 'Wii', 'Multi-platform'],
                   'Publishers':['PUBG Corporation', 'Electronic Arts', 'Rockstar Games', 'Nintendo' , 'Xbox Game Studios'],
                   'Total_Year':random.sample(range(10, 30), 5),
                   'Sales':random.sample(range(100, 300), 5)
                   })
df1.head()
df1.tail()

,Name,Genre,Platform,Publishers,Total_Year,Sales
0,PUBG: Battlegrounds,Battle royale,PC,PUBG Corporation,29,119
1,Tetris (EA),Puzzle,Multi-platform,Electronic Arts,16,108
2,Grand Theft Auto V,Action-adventure,Multi-platform,Rockstar Games,20,100
3,Wii Sports,Sports simulation,Wii,Nintendo,17,233
4,Minecraft,"Survival,Sandbox",Multi-platform,Xbox Game Studios,13,211

##### pd.melt(**frame**, id_vars=None, value_vars=None, var_name=None, value_name='value', col_level=None, ignore_index=True)

* id_vars: Column(s) to use as identifier variables.
* value_vars: Column(s) to unpivot. If not specified, uses all columns not set in id_vars.
> col_level ✅

In [ ]:
pd.melt(df1, id_vars=['Name', 'Platform'])

                   Name        Platform    variable              value
0   PUBG: Battlegrounds              PC       Genre      Battle royale
1           Tetris (EA)  Multi-platform       Genre             Puzzle
2    Grand Theft Auto V  Multi-platform       Genre   Action-adventure
3            Wii Sports             Wii       Genre  Sports simulation
4             Minecraft  Multi-platform       Genre   Survival,Sandbox
5   PUBG: Battlegrounds              PC  Publishers   PUBG Corporation
6           Tetris (EA)  Multi-platform  Publishers    Electronic Arts
7    Grand Theft Auto V  Multi-platform  Publishers     Rockstar Games
8            Wii Sports             Wii  Publishers           Nintendo
9             Minecraft  Multi-platform  Publishers  Xbox Game Studios
10  PUBG: Battlegrounds              PC  Total_Year                 29
11          Tetris (EA)  Multi-platform  Total_Year                 16
12   Grand Theft Auto V  Multi-platform  Total_Year                 20
13           Wii Sports             Wii  Total_Year                 17
14            Minecraft  Multi-platform  Total_Year                 13
15  PUBG: Battlegrounds              PC       Sales                119
16          Tetris (EA)  Multi-platform       Sales                108
17   Grand Theft Auto V  Multi-platform       Sales                100
18           Wii Sports             Wii       Sales                233
19            Minecraft  Multi-platform       Sales                211

In [ ]:
df1.melt(id_vars=['Name'], value_vars=['Total_Year', 'Sales'], var_name='Game Success', value_name='Numerical')

                  Name Game Success  Numerical
0  PUBG: Battlegrounds   Total_Year         29
1          Tetris (EA)   Total_Year         16
2   Grand Theft Auto V   Total_Year         20
3           Wii Sports   Total_Year         17
4            Minecraft   Total_Year         13
5  PUBG: Battlegrounds        Sales        119
6          Tetris (EA)        Sales        108
7   Grand Theft Auto V        Sales        100
8           Wii Sports        Sales        233
9            Minecraft        Sales        211

In [ ]:
df1 = pd.DataFrame({'State':['Gujrat', 'Haryana', 'Rajasthan', 'Punjab', 'Uttar Pradesh'], 'Score1':[34, 46, 42, np.nan, 29], 'Score2':[45, 43, 34, 38, 26]})
df1['Pass_Status'] = np.logical_and(df1['Score1'] > 40, df1['Score2'] > 40)
print(df1)

           State  Score1  Score2  Pass_Status
0         Gujrat    34.0      45        False
1        Haryana    46.0      43         True
2      Rajasthan    42.0      34        False
3         Punjab     NaN      38        False
4  Uttar Pradesh    29.0      26        False

##### dataFrame.sort_values(**by**, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)

Series.sort_values(axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)

* ascending: Can pass a list for multi-column sorting.
* kind: 'quicksort', 'mergesort', 'heapsort', 'stable'
* na_position: 'first' or 'last'
* key: Vectorized function applied to values prior to sorting.

In [ ]:
df1.sort_values(by=['State', 'Score1'], ascending=[True, False], na_position='first')

           State  Score1  Score2  Pass_Status
0         Gujrat    34.0      45        False
1        Haryana    46.0      43         True
3         Punjab     NaN      38        False
2      Rajasthan    42.0      34        False
4  Uttar Pradesh    29.0      26        False

In [ ]:
df1.sort_values(by='State', key=lambda x: x.str.len())

           State  Score1  Score2  Pass_Status
0         Gujrat    34.0      45        False
3         Punjab     NaN      38        False
1        Haryana    46.0      43         True
2      Rajasthan    42.0      34        False
4  Uttar Pradesh    29.0      26        False

##### Series.sort_index(axis=0, level=None, ascending=True, inplace=False, kind='quicksort', na_position='last', sort_remaining=True, ignore_index=False, key=None)

> level, sort_remaining ✅

In [ ]:
df1.sort_index(axis=1)

   Pass_Status  Score1  Score2          State
0        False    34.0      45         Gujrat
1         True    46.0      43        Haryana
2        False    42.0      34      Rajasthan
3        False     NaN      38         Punjab
4        False    29.0      26  Uttar Pradesh

##### DataFrame.query(expr, inplace=False, **kwargs)
> **kwargs ✅

In [ ]:
df.query('Week1 > 2 and index == "Wed"')

     Week1  Week2  Week3  Week4  NextMonth  NewWeek2
Wed      3     10     17     24         31         7

##### DataFrame.where(cond, other=np.nan, inplace=False, axis=None, level=None, errors='raise', try_cast=False)

> level, try_cast ✅

In [ ]:
df['Week2'].where(lambda x: x%5!=0, other='Laddu')

Mon        8
Tue        9
Wed    Laddu
Thu       11
Fri       12
Name: Week2, dtype: object

##### DataFrame.drop(labels=None, axis=0, index=None, **columns=None**, level=None, inplace=False, errors='raise')

Series.drop(labels=None, axis=0, index=None, level=None, inplace=False, errors='raise')

* index: Alternative to (labels + axis=0)
* columns: Alternative to (labels + axis=1)
* inplace: If true, modifies the original object
> level ✅

In [ ]:
df.drop(df[df.Week1 == 2].index) # Only Columns

     Week1  Week2  Week3  Week4  NextMonth
Mon      1      8     15     22         29
Wed      3     10     17     24         31
Thu      4     11     18     25          1
Fri      5     12     19     26          2

In [ ]:
cols_to_drop = df.columns[df.loc['Tue'] == 2]
df.drop(columns=cols_to_drop)

     Week2  Week3  Week4  NextMonth
Mon      8     15     22         29
Tue      9     16     23         30
Wed     10     17     24         31
Thu     11     18     25          1
Fri     12     19     26          2

In [ ]:
df.drop(columns=['Week1']) # Only Columns

     Week2  Week3  Week4  NextMonth
Mon      8     15     22         29
Tue      9     16     23         30
Wed     10     17     24         31
Thu     11     18     25          1
Fri     12     19     26          2

##### DataFrame.rename(mapper=None, index=None, columns=None, axis=None, copy=None, inplace=False, level=None, errors='ignore')

* mapper: dict or function. Paired with axis (0 / 'index' or 1 / 'columns')
* index / columns: dict or function
* copy: If True, create new DataFrame when possible.

In [ ]:
df.rename(columns={'NextMonth': 'NewWeek1'})

     Week1  Week2  Week3  Week4  NewWeek1
Mon      1      8     15     22        29
Tue      2      9     16     23        30
Wed      3     10     17     24        31
Thu      4     11     18     25         1
Fri      5     12     19     26         2

In [ ]:
df.rename(mapper=str.upper, axis=1)

     WEEK1  WEEK2  WEEK3  WEEK4  NEXTMONTH
Mon      1      8     15     22         29
Tue      2      9     16     23         30
Wed      3     10     17     24         31
Thu      4     11     18     25          1
Fri      5     12     19     26          2

##### DataFrame.insert(loc, column, value, allow_duplicates=False)
* loc: Index position of column
* allow_duplicates: If false, throws a ValueError if the column name already exists

In [ ]:
df.insert(loc=5, column="NewWeek2", value=[5, 6, 7, 8, 9])
print(df)

     Week1  Week2  Week3  Week4  NextMonth  NewWeek2
Mon      1      8     15     22         29         5
Tue      2      9     16     23         30         6
Wed      3     10     17     24         31         7
Thu      4     11     18     25          1         8
Fri      5     12     19     26          2         9

| Sr No. | Attribute | Sr No. | Attribute | Sr No. | Attribute |
| --- | --- | --- | --- | --- | --- |
| 1. | `a.shape` | 2. | `a.shape[0]` | 3. | `a.shape[1]` |
| 4. | `a.columns` | 5. | `a.index` | 6. | `a.size` |
| 7. | `a.dtypes` | 8. | `a.ndim` | 9. | `a.info()` |
| 10. | `a.describe()` | 11. | `a.head()` | 12. | `a.tail()` |

In [ ]:
df.columns[0:2]

Index(['Week1', 'Week2'], dtype='object')

#### 1. Index-Based vs. Label-Based Selection
*   **loc (Label-based):** Selects data using row and column text labels.
*   **iloc (Index-based):** Selects data using zero-based integer index positions.

| Operation | loc[] | iloc[] |
| :--- | :--- | :--- |
| **Single Row** | `df.loc['r2']` | `df.iloc[1]` |
| **Single Column** | `df.loc[:, 'c2']` | `df.iloc[:, 1]` |
| **Multiple Rows** | `df.loc[['r2', 'r3']]` | `df.iloc[[1, 2]]` |
| **Multiple Columns** | `df.loc[:, ['c2', 'c3']]` | `df.iloc[:, [1, 2]]` |
| **Row Range** | `df.loc['r1':'r4']` *(inclusive)* | `df.iloc[0:4]` *(exclusive stop)* |
| **Column Range** | `df.loc[:, 'c1':'c4']` *(inclusive)* | `df.iloc[:, 0:4]` *(exclusive stop)* |
| **Alternate Rows** | `df.loc['r1':'r5':2]` | `df.iloc[0:5:2]` |
| **Alternate Columns** | `df.loc[:, 'c1':'c5':2]` | `df.iloc[:, 0:5:2]` |
| **Conditional Filter** | `df.loc[df['Fee'] >= 1000]` | `df.iloc[list(df['Fee'] >= 1000)]` |
| **Lambda Function** | `df.loc[lambda x:x[3]]` | `df.iloc[lambda x:x[3]]` |

In [ ]:
df.NextMonth>20

Mon     True
Tue     True
Wed     True
Thu    False
Fri    False
Name: NextMonth, dtype: bool

In [ ]:
df['NextMonth']<20

Mon    False
Tue    False
Wed    False
Thu     True
Fri     True
Name: NextMonth, dtype: bool

In [ ]:
df[df['NextMonth']<20].Week1[1] # df[df['NextMonth']<20].index[1]

/tmp/ipykernel_573/3269947900.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df[df['NextMonth']<20].Week1[1] # df[df['NextMonth']<20].index[1]

np.int64(5)

In [ ]:
df.loc[df['NextMonth']>20]
# df[df['NextMonth']>20]
# df.loc[df.NextMonth>20]
# df[df.NextMonth>20]

     Week1  Week2  Week3  Week4  NextMonth  NewWeek2
Mon      1      8     15     22         29         5
Tue      2      9     16     23         30         6
Wed      3     10     17     24         31         7

In [ ]:
df.loc[lambda x:x['NextMonth']>20]

     Week1  Week2  Week3  Week4  NextMonth  NewWeek2
Mon      1      8     15     22         29         5
Tue      2      9     16     23         30         6
Wed      3     10     17     24         31         7

In [ ]:
df.loc[["Mon", "Thu"], ["Week1", "NextMonth"]]

     Week1  NextMonth
Mon      1         29
Thu      4          1

In [ ]:
df.loc["Mon":"Wed", "Week1":"Week3"]

     Week1  Week2  Week3
Mon      1      8     15
Tue      2      9     16
Wed      3     10     17

In [ ]:
df.loc["Mon":"Wed", ["Week1", "NextMonth"]]

     Week1  NextMonth
Mon      1         29
Tue      2         30
Wed      3         31

In [ ]:
df.loc[['Mon']]

     Week1  Week2  Week3  Week4  NextMonth  NewWeek2
Mon      1      8     15     22         29         5

In [ ]:
df.loc['Sat'] = [6, 13, 20, 27, 3, 11]
print(df)

     Week1  Week2  Week3  Week4  NextMonth  NewWeek2
Mon      1      8     15     22         29         5
Tue      2      9     16     23         30         6
Wed      3     10     17     24         31         7
Thu      4     11     18     25          1         8
Fri      5     12     19     26          2         9
Sat      6     13     20     27          3        11

In [ ]:
df.loc[len(df)] = [7, 14, 21, 28, 4, 12]
print(df)

     Week1  Week2  Week3  Week4  NextMonth  NewWeek2
Mon      1      8     15     22         29         5
Tue      2      9     16     23         30         6
Wed      3     10     17     24         31         7
Thu      4     11     18     25          1         8
Fri      5     12     19     26          2         9
Sat      6     13     20     27          3        11
6        7     14     21     28          4        12

#### 2.1 GroupBy Process: The Split-Apply-Combine Strategy
It categorizes data based on custom keys using Hadley Wickham's **Split-Apply-Combine** workflow:

1.  **Split:** Breaks the DataFrame into smaller subsets based on unique key values.
2.  **Apply:** Applies an aggregation function to each independent group.
3.  **Combine:** Combines the individual aggregated results back into a single structured output array.
```
Input DataFrame     Split by Key      Apply Function
┌─────┬──────┐      ┌───┬───┐         ┌───┬───┐
│ Key │ Data │      │ A │ 1 │ ───┐    │ A │ 5 │      Combine Output
├─────┼──────┤      │ A │ 4 │    │    └───┴───┘      ┌───┬──────┐
│  A  │  1   │      └───┴───┘    │                   │ A │  5   │
│  B  │  2   │      ┌───┬───┐    │    ┌───┬───┐      ├───┼──────┤
│  C  │  3   │ ───> │ B │ 2 │ ───┼──> │ B │ 7 │ ───> │ B │  7   │
│  A  │  4   │      │ B │ 5 │    │    └───┴───┘      ├───┼──────┤
│  B  │  5   │      └───┴───┘    │                   │ C │  9   │
│  C  │  6   │      ┌───┬───┐    │    ┌───┬───┐      └───┴──────┘
└─────┴──────┘      │ C │ 3 │ ───┘    │ C │ 9 │
                    │ C │ 6 │         └───┴───┘
                    └───┴───┘
```
```
Input DataFrame                    df.groupby(['foo', 'bar'])['baz'].sum();
┌───┬──────┬─────┬─────┬─────┐     ┌──────┬─────┬──────┐
│   │ foo  │ bar │ baz │ zoo │     │ foo  │ bar │ baz  │
├───┼──────┼─────┼─────┼─────┤     ├──────┼─────┼──────┤
│ 0 │ one  │  A  │  1  │  x  │     │ one  │  A  │ 1+2  │
│ 1 │ one  │  A  │  2  │  y  │     ├──────┼─────┼──────┤
│ 2 │ one  │  B  │  3  │  z  │     │ one  │  B  │  3   │
│ 3 │ two  │  A  │  4  │  q  │ ───>├──────┼─────┼──────┤
│ 4 │ two  │  B  │  5  │  w  │     │ two  │  A  │  4   │
│ 5 │ two  │  B  │  6  │  t  │     ├──────┼─────┼──────┤
└───┴──────┴─────┴─────┴─────┘     │ two  │  B  │ 5+6  │
                                   └──────┴─────┴──────┘
```

#### 2.2 Pivot Table

A multi-dimensional aggregation and reshaping tool that reorganizes flat tabular data into a two-dimensional grid. It maps specified keys to the row index (y-axis) and column headers (x-axis), calculating summary statistics across their intersections.
```
Input DataFrame                    df.pivot_table(index='foo', columns='bar', values='baz', aggfunc='sum')
┌───┬──────┬─────┬─────┬─────┐     ┌──────┬───────┬───────┐
│   │ foo  │ bar │ baz │ zoo │     │ bar  │   A   │   B   │
├───┼──────┼─────┼─────┼─────┤     ├──────┼───────┼───────┤
│ 0 │ one  │  A  │  1  │  x  │     │ foo  │       │       │
│ 1 │ one  │  A  │  2  │  y  │     ├──────┼───────┼───────┤
│ 2 │ one  │  B  │  3  │  z  │ ───>│ one  │  1+2  │   3   │
│ 3 │ two  │  A  │  4  │  q  │     ├──────┼───────┼───────┤
│ 4 │ two  │  B  │  5  │  w  │     │ two  │   4   │  5+6  │
│ 5 │ two  │  B  │  6  │  t  │     └──────┴───────┴───────┘
└───┴──────┴─────┴─────┴─────┘
```

#### 2.3 Cross-Tabulation

A specialized statistical matrix (contingency table) designed to compute frequency distributions and relative percentages across categorical or discrete variables. It analyzes how two or more categorical factors interact.

* **Frequency Table:** Shows the distribution of values in a dataset by counting the number of occurrences (or relative percentages) of unique categorical values within a dataset.
```
Input Lists                        pd.crosstab(index=List_1, columns=List_2, values=List_3, aggfun=sum)
┌────────┬─────────┬────────┐      ┌────────┬────────┬─────────┐
│ List_1 │ List_2  │ List_3 │      │ List_2 │ Inside │ Outside │
├────────┼─────────┤────────┤      ├────────┼────────┼─────────┤
│ Bob    │ Inside  │   10   │      │ List_1 │        │         │
│ Bob    │ Outside │   15   │      ├────────┼────────┼─────────┤
│ Sally  │ Outside │   20   │ ───> │ Bob    │   40   │   15    │
│ Bob    │ Inside  │   30   │      ├────────┼────────┼─────────┤
└────────┴─────────┴────────┘      │ Sally  │    0   │   20    │
                                   └────────┴────────┴─────────┘
```

| Feature | groupby() | pivot_table() | crosstab() |
| --- | --- | --- | --- |
| **Primary Purpose** | Row-wise grouping & multi-column aggregation | Reshaping data into a 2D matrix grid | Frequency counting & cross-relationship analysis |
| **Output Structure** | Flat/1D Series or MultiIndex DataFrame | 2D Matrix | 2D Contingency Grid |
| **Input Type** | DataFrame | DataFrame | Raw lists, Series, or NumPy arrays |
| **Default Aggregation** | None (requires explicit method) | Yes | Yes |

> Methods of DataFrame and Series objects. We can use numpy operations as well.

| Sr No. | Operation | Function |
| :--- | :--- | :--- |
| 1. | Sum | sum() |
| 2. | Product | prod() |
| 3. | Mean | mean() |
| 4. | Median | median() |
| 5. | Maximun |  max() |
| 6. | Minimum | min() |
| 7. | Standard Deviation | std() |
| 8. | Mean Absolute Deviation | mad() |
| 9. | Variance | var() |
| 10. | Count | count() |
| 11. | First | first() |
| 12. | Last | last() |

##### Series.groupby(by=None, axis=0, level=None, as_index=True, sort=True,
group_keys=True, observed=False, dropna=True)

* as_index: If true, group keys become the row index of the output.
* sort: If true, sorts group keys in ascending order.
> level, group_keys, observed, dropna ✅

In [ ]:
import pandas as pd
df2 = pd.DataFrame({'Department':['HR', 'IT', 'Finance', 'IT', 'HR'], 'Salary':[5000, 6000, 7000, 5500, 6500], 'WorkForce':[5, 7, 10, 7, 10]})
grouped = df2.groupby('Department')['Salary'].sum()
print(grouped)

Department
Finance     7000
HR         11500
IT         11500
Name: Salary, dtype: int64

In [ ]:
df2.groupby('Department')['Salary'].agg(['mean', 'count'])

              mean  count
Department
Finance     7000.0      1
HR          5750.0      2
IT          5750.0      2

In [ ]:
df2.groupby('Department').agg({'Salary':'mean', 'WorkForce':'count'})

            Salary  WorkForce
Department
Finance     7000.0          1
HR          5750.0          2
IT          5750.0          2

In [ ]:
df2.groupby('Department').agg({'Salary':'mean', 'WorkForce':'count'}).reset_index()

  Department  Salary  WorkForce
0    Finance  7000.0          1
1         HR  5750.0          2
2         IT  5750.0          2

In [ ]:
df2['Avg_Salary'] = df2.groupby('Department')['Salary'].transform('mean')
print(df2)

  Department  Salary  WorkForce  Avg_Salary
0         HR    5000          5      5750.0
1         IT    6000          7      5750.0
2    Finance    7000         10      7000.0
3         IT    5500          7      5750.0
4         HR    6500         10      5750.0

##### pd.pivot_table(**data**, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=False, sort=True)

> dropna, observed ✅

In [ ]:
pivot = pd.pivot_table(df2, values='Salary', index='Department', columns='WorkForce')
print(pivot)

WorkForce       5       7       10
Department
Finance        NaN     NaN  7000.0
HR          5000.0     NaN  6500.0
IT             NaN  5750.0     NaN

In [ ]:
pd.pivot_table(df2, values='Salary', index='Department', columns='WorkForce', aggfunc=['sum', 'max'], fill_value=0, margins=True, margins_name='Total', sort=False)

             sum                        max
WorkForce      5      7     10  Total     5     7    10 Total
Department
HR          5000      0   6500  11500  5000     0  6500  6500
IT             0  11500      0  11500     0  6000     0  6000
Finance        0      0   7000   7000     0     0  7000  7000
Total       5000  11500  13500  30000  5000  6000  7000  7000

##### pd.crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins=False, margins_name='All', dropna=True, normalize=False)

> dropna ✅

In [ ]:
gender = pd.Series(['Male', 'Female', 'Female', 'Male', 'Female'])
preference = pd.Series(['Python', 'R', 'Python', 'Python', 'R'])
ct = pd.crosstab(gender, preference)
print(ct)

col_0   Python  R
row_0
Female       1  2
Male         2  0

In [ ]:
scores = [85, 90, 78, 92, 88]
department = pd.Series(['IT', 'IT', 'HR', 'HR', 'IT'])
ct = pd.crosstab(index=[gender, department], columns=preference, values=scores, rownames=['gender', 'department'], colnames=['preference'], aggfunc='mean')
print(ct) # ValueError: aggfunc cannot be None when values are passed.

preference         Python     R
gender department
Female HR            78.0   NaN
       IT             NaN  89.0
Male   HR            92.0   NaN
       IT            85.0   NaN

| normalize= | Type | What It Does | Row/Column Sums |
| --- | --- | --- | --- |
| **`False`** | bool | Keeps raw frequency counts. | Counts sum to total samples. |
| **`True`** / **`'all'`** | bool / str | Divides every cell by the **grand total** of all values. | The entire table sums to $1.0$ ($100\%$). |
| **`'index'`** | str | Divides each cell by its **row total**. | Each row sums to $1.0$ ($100\%$). |
| **`'columns'`** | str | Divides each cell by its **column total**. | Each column sums to $1.0$ ($100\%$). |

#### 3. Handling Missing Data
Pandas represents missing entries using two values:
*   `None`: Python's built-in singleton object.
*   `NaN` (Not a Number): IEEE floating-point representation.
Pandas treats `None` and `NaN` as interchangeable null values.

```
               ┌─ Checking Nulls ─────┬─ isnull() (True if missing)
               │                      └─ notnull() (True if present)
               │
               ├─ Imputing / Filling ─┬─ fillna(), ffill(), bfill()
Missing Data ──┤                      ├─ replace()
  Handling     │                      └─ interpolate()
               │
               └─ Dropping Values ────── dropna()
```
```
                ┌─────────────────────────────────┐
                │ Methods to Handle Missing Value │
                └────────────────┬────────────────┘
       ┌─────────────────────────┴────────────────────┐
┌──────┴─────┐                                  ┌─────┴────┐
│ Imputation │                                  │ Deletion │
└───┬────────┘                                  └─────┬────┘
    ├─ Mean ─── Numerical data, normal distribution   └── Use when: < 5% missing data
    ├─ Median ─ Numerical data, skewed distribution   & no meaningful pattern
    └─ Mode ─── Categorical data (e.g., "Weather")    (MCAR - Missing Completely At Random)
```

In [ ]:
import pandas as pd
df3 = pd.DataFrame({'Gender':['M', np.nan, np.nan, 'F'], 'Strength':[30, 40, np.nan, np.nan], 'Sports':[np.nan, 'Cricket', 'Badminton', 'Hockey']})
df3.isnull()

   Gender  Strength  Sports
0   False     False    True
1    True     False   False
2    True      True   False
3   False      True   False

In [ ]:
df3.isnull().sum()

Gender      2
Strength    2
Sports      1
dtype: int64

##### DataFrame.fillna(value=None, method=None, axis=None, inplace=False, limit=None, downcast=None)

Series.fillna(value=None, method=None, axis=None, inplace=False, limit=None, downcast=None)

* method: 'ffill' / 'pad' or 'bfill' / 'backfill'
* limit: Maximum number of consecutive NaN values to fill along the specified axis.
> downcast ✅

In [ ]:
df3.fillna(0, limit=1)

  Gender  Strength     Sports
0      M      30.0          0
1      0      40.0    Cricket
2    NaN       0.0  Badminton
3      F       NaN     Hockey

In [ ]:
df3['Gender'].fillna('Other')
print(df3)

  Gender  Strength     Sports
0      M      30.0        NaN
1    NaN      40.0    Cricket
2    NaN       NaN  Badminton
3      F       NaN     Hockey

In [ ]:
df3.fillna({'Strength':df3['Strength'].mean(), 'Gender':'GAY'})

  Gender  Strength     Sports
0      M      30.0        NaN
1    GAY      40.0    Cricket
2    GAY      35.0  Badminton
3      F      35.0     Hockey

In [ ]:
df3.ffill()

  Gender  Strength     Sports
0      M      30.0        NaN
1      M      40.0    Cricket
2      M      40.0  Badminton
3      F      40.0     Hockey

In [ ]:
df3.bfill()

  Gender  Strength     Sports
0      M      30.0    Cricket
1      F      40.0    Cricket
2      F       NaN  Badminton
3      F       NaN     Hockey

##### Series.replace(to_replace=None, value=None, inplace=False, limit=None, regex=False, method=None)

* limit: Maximum number of consecutive matches to fill
* method: Use only when value=None
> regex ✅

In [ ]:
df3.replace('Cricket', 'Football')

  Gender  Strength     Sports
0      M      30.0        NaN
1    NaN      40.0   Football
2    NaN       NaN  Badminton
3      F       NaN     Hockey

In [ ]:
df3.replace(['M', np.nan], 'Male')

  Gender Strength     Sports
0   Male     30.0       Male
1   Male     40.0    Cricket
2   Male     Male  Badminton
3      F     Male     Hockey

In [ ]:
df3.replace(['M', 'Cricket'], ['MALE', 'Football'])
# df3.replace({'M': 'Male', 'Cricket': 'Football'})
# df3.replace({'Gender': {'M': 'Male', 'F': 'Female'}, 'Sports': {'Cricket': 'Football'}})

  Gender  Strength     Sports
0   MALE      30.0        NaN
1    NaN      40.0   Football
2    NaN       NaN  Badminton
3      F       NaN     Hockey

##### Series.interpolate(method=linear, axis=0, limit=None, inplace=False, limit_direction=None, limit_area=None, downcast=None, **kwargs)

* method: pad, ffill, bfill, index / values, etc.
* limit: Maximum number of consecutive NaN values to fill.
* limit_direction: 'forward', 'backward' or 'both'
* limit_area: None, 'inside' or 'outside'
> downcast, **kwargs ✅

In [ ]:
import pandas as pd
x = pd.Series([10.0, np.nan, np.nan, 40.0], index=pd.to_datetime(['2026-01-01', '2026-01-02', '2026-01-04', '2026-01-06']))
x.interpolate(method='time')

2026-01-01    10.0
2026-01-02    16.0
2026-01-04    28.0
2026-01-06    40.0
dtype: float64

In [ ]:
x.interpolate(method='linear')

2026-01-01    10.0
2026-01-02    20.0
2026-01-04    30.0
2026-01-06    40.0
dtype: float64

In [ ]:
x.interpolate(method='index')

2026-01-01    10.0
2026-01-02    16.0
2026-01-04    28.0
2026-01-06    40.0
dtype: float64

In [ ]:
x.interpolate(method='nearest')

2026-01-01    10.0
2026-01-02    10.0
2026-01-04    40.0
2026-01-06    40.0
dtype: float64

In [ ]:
x = pd.Series([1, 4, np.nan, 16, 25])
print(x.interpolate(method='polynomial', order=1)) # num of valid points (m) > order(k)
print(x.interpolate(method='polynomial', order=2))
print(x.interpolate(method='polynomial', order=3))

0     1.0
1     4.0
2    10.0
3    16.0
4    25.0
dtype: float64
0     1.0
1     4.0
2     9.0
3    16.0
4    25.0
dtype: float64
0     1.0
1     4.0
2     9.0
3    16.0
4    25.0
dtype: float64

In [ ]:
print(x.interpolate(method='spline', order=1)) # num of valid points (m) > order(k)
print(x.interpolate(method='spline', order=2)) # s.interpolate(method='quadratic')
print(x.interpolate(method='spline', order=3)) # s.interpolate(method='cubic')

0     1.000000
1     4.000000
2    10.933653
3    16.000000
4    25.000000
dtype: float64
0     1.0
1     4.0
2     9.0
3    16.0
4    25.0
dtype: float64
0     1.0
1     4.0
2     9.0
3    16.0
4    25.0
dtype: float64

In [ ]:
print(x.interpolate(method='zero'))
print(x.interpolate(method='slinear'))
print(x.interpolate(method='pchip'))
print(x.interpolate(method='akima'))
print(x.interpolate(method='cubicspline'))
print(x.interpolate(method='barycentric'))
print(x.interpolate(method='krogh'))
print(x.interpolate(method='from_derivatives'))

0     1.0
1     4.0
2     4.0
3    16.0
4    25.0
dtype: float64
0     1.0
1     4.0
2    10.0
3    16.0
4    25.0
dtype: float64
0     1.000000
1     4.000000
2     9.123377
3    16.000000
4    25.000000
dtype: float64
0     1.00
1     4.00
2     9.25
3    16.00
4    25.00
dtype: float64
0     1.0
1     4.0
2     9.0
3    16.0
4    25.0
dtype: float64
0     1.0
1     4.0
2     9.0
3    16.0
4    25.0
dtype: float64
0     1.0
1     4.0
2     9.0
3    16.0
4    25.0
dtype: float64
0     1.0
1     4.0
2    10.0
3    16.0
4    25.0
dtype: float64

In [ ]:
x = pd.Series([np.nan, np.nan, 10.0, np.nan, np.nan, np.nan, 50.0, np.nan, np.nan])
# Index:       0       1       2     3       4       5       6     7       8
# Region:     [-- Leading --] [--- Interior Gap (3 NaNs) ---] [-- Trailing ---]

In [ ]:
x.interpolate(limit=1) # Change at 3, 7

0     NaN
1     NaN
2    10.0
3    20.0
4     NaN
5     NaN
6    50.0
7    50.0
8     NaN
dtype: float64

In [ ]:
x.interpolate(limit_area='inside') # Change at 3, 4, 5

0     NaN
1     NaN
2    10.0
3    20.0
4    30.0
5    40.0
6    50.0
7     NaN
8     NaN
dtype: float64

In [ ]:
x.interpolate(limit_direction='forward') # Change at 3, 4, 5, 7, 8
# x.interpolate()

0     NaN
1     NaN
2    10.0
3    20.0
4    30.0
5    40.0
6    50.0
7    50.0
8    50.0
dtype: float64

In [ ]:
x.interpolate(limit=1, limit_direction='both') # Change at 1, 3, 5, 7

0     NaN
1    10.0
2    10.0
3    20.0
4     NaN
5    40.0
6    50.0
7    50.0
8     NaN
dtype: float64

In [ ]:
x.interpolate(limit_area='inside', limit=1, limit_direction='both') # Change at 3, 5

0     NaN
1     NaN
2    10.0
3    20.0
4     NaN
5    40.0
6    50.0
7     NaN
8     NaN
dtype: float64

##### DataFrame.dropna(axis=0, how='any', **thresh=None, subset=None**, inplace=False, ignore_index=False)

Series.dropna(axis=0, inplace=False, how=None, ignore_index=False)

* how: 'any' (if at least one NaN) / 'all' (if all entries are NaN)
* thresh: Sets a threshold for non-null values. Keeps that have at least N (non-null) entries. (Overrides how if provided).

In [ ]:
y = pd.DataFrame({'A':[1.0, np.nan, np.nan, 4.0], 'B':[10.0, 20.0, np.nan, 40.0], 'C':[np.nan, np.nan, np.nan, np.nan], 'D':[10.0, 20.0, 30.0, 40.0]})
y.dropna(how='any')

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
y.dropna(subset=['A', 'B'])

     A     B   C     D
0  1.0  10.0 NaN  10.0
3  4.0  40.0 NaN  40.0

In [ ]:
y.dropna(thresh=2, ignore_index=True)

     A     B   C     D
0  1.0  10.0 NaN  10.0
1  NaN  20.0 NaN  20.0
2  4.0  40.0 NaN  40.0

##### Categorical Data & Feature Encoding
Machine learning models require numerical input, necessitating categorical encoding.

*   **Nominal Encoding:** Discrete categories with no inherent ordering (e.g., states, colors).
*   **Ordinal Encoding:** Discrete categories with an explicit rank or order. Assigns an integer (0, 1, 2...) to each unique category.

##### Encoding Techniques
*   **One-Hot Encoding:** Maps nominal values to binary vectors (0 or 1).
    *   Dummy Variable Trap: To prevent perfect multicollinearity, one column must be dropped, keeping (N-1) dummy columns.
    *   Curse of Dimensionality: Applying One-Hot Encoding to features with high cardinality inflate dataset dimensionality.
*   **Label / Map Encoding:** Maps ordered categories directly to incremental integers reflecting their rank.

In [ ]:
import pandas as pd
z = pd.DataFrame({'Size':['Small', 'Medium', 'Large']})
size_map = {'Small': 0, 'Medium': 1, 'Large': 2}
z['Size'].map(size_map)

0    0
1    1
2    2
Name: Size, dtype: int64

In [ ]:
z = pd.DataFrame({'Color':['Red', 'Blue', 'Green']})
pd.get_dummies(z, columns=['Color'])

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False

##### Statistical Functions
*   `pct_change()`: Calculates percentage change from a previous element to the current element.
*   `cov() (Covariance)`: Measures the direction of a linear relationship between two variables.
*   `corr() (Correlation)`: Measures both the strength and direction of a linear relationship on a scale from $-1.0$ to $+1.0$.

In [ ]:
z = pd.DataFrame({'Stock_A': [10, 20, 30, 40], 'Stock_B': [15, 25, 35, 45]})
z['Stock_A'].pct_change()

0         NaN
1    1.000000
2    0.500000
3    0.333333
Name: Stock_A, dtype: float64

In [ ]:
z.cov()

            Stock_A     Stock_B
Stock_A  166.666667  166.666667
Stock_B  166.666667  166.666667

In [ ]:
z.corr()

         Stock_A  Stock_B
Stock_A      1.0      1.0
Stock_B      1.0      1.0

#### 4. Windowing Operations
Unlike standard Aggregation functions that collapse multiple rows into a single summary row, a Window Function maintains the original DataFrame shape—it returns a calculated result for every single row in the dataset. We generally use the Windows functions if we are dealing
with time series data.
```
          ┌───────────────────────────────┐
          │    Python Window Functions    │
          └───────────────┬───────────────┘
      ┌───────────────────┼────────────────────────┐
┌─────┴─────┐      ┌──────┴──────┐         ┌───────┴───┐
│ Aggregate │      │   Ranking   │         │   Value   │
└──┬────────┘      └────┬────────┘         └─────┬─────┘
   ├── Group            ├── Row Numbers          ├── Lag/Lead
   ├── Rolling          │    ├── reset_index()   └── First/Last/nth Value
   └── Expanding        │    └── cumcount()
                        ├── Rank
                        │    ├── default_rank
                        │    ├── min_rank
                        │    ├── NA_bottom
                        │    └── descending
                        ├── Dense Rank
                        ├── Percent
                        └── N-Tile / qcut()
```
```
             ┌───────────────────────────────┐
             │    Pandas Window Functions    │
             └───────────────┬───────────────┘
         ┌───────────────────┼──────────────────┐
┌────────┴────────┐  ┌───────┴──────┐  ┌────────┴───────┐
│   1. Rolling    │  │ 2. Expanding │  │ 3. Exponential │
│ (Moving Window) │  │ (Cumulative) │  │  (EWMA / EWM)  │
└─────────────────┘  └──────────────┘  └────────────────┘
```

##### DataFrame.rolling(window, min_periods=None, center=False, win_type=None, on=None, axis=0, closed=right, step=None)

* window: If offset string (e.g., '2D', '5h', '10s'): Time-based window based on timestamps (requires DatetimeIndex or on parameter).
* min_periods: Minimum observations required in the accumulating window before producing a non-NaN output.
* win_type: Weight distribution across window points (requires SciPy).
* on: Name of a column containing datetimes to use for time-based rolling instead of using the DataFrame index.
* closed: • 'right' (T-N, T] • 'left' [T-N, T) • 'both' [T-N, T] • 'neither' (T-N, T) **(for time-based window)**
* step: Evaluates the window every $N$-th step instead of every single row.

In [ ]:
df4 = pd.DataFrame({'Date': pd.date_range(start='2026-01-01', periods=5, freq='D'), 'Sales':[100, 120, 110, 150, 200]}).set_index('Date')
df4['Rolling_3D_Mean'] = df4['Sales'].rolling(window=3).mean()
df4['Rolling_3D_Mean_Center'] = df4['Sales'].rolling(window=3, center=True).mean()
df4['Rolling_3D_Min1'] = df4['Sales'].rolling(window=3, min_periods=1).mean() # (to prevents leading NaNs)
print(df4)

            Sales  Rolling_3D_Mean  Rolling_3D_Mean_Center  Rolling_3D_Min1
Date
2026-01-01    100              NaN                     NaN       100.000000
2026-01-02    120              NaN              110.000000       110.000000
2026-01-03    110       110.000000              126.666667       110.000000
2026-01-04    150       126.666667              153.333333       126.666667
2026-01-05    200       153.333333                     NaN       153.333333

In [ ]:
df5 = pd.DataFrame({"X": 1}, index=[pd.Timestamp("20130101 09:00:01"), pd.Timestamp("20130101 09:00:02"), pd.Timestamp("20130101 09:00:03")])
df5["right"] = df5['X'].rolling("2s", closed="right").sum()
df5["both"] = df5.rolling("2s", closed="both").X.sum() # Other Syntax
df5["left"] = df5.rolling("2s", closed="left").X.sum()
df5["neither"] = df5.rolling("2s", closed="neither").X.sum()
print(df5)

                     X  right  both  left  neither
2013-01-01 09:00:01  1    1.0   1.0   NaN      NaN
2013-01-01 09:00:02  1    2.0   2.0   1.0      1.0
2013-01-01 09:00:03  1    2.0   3.0   2.0      1.0

##### DataFrame.rolling().apply(func, raw=False, engine='python', engine_kwargs=None, args=(), kwargs={})

* func: A custom Python function that accepts an array/Series representing the current window and returns a single numerical scalar value.
* raw: • True: Passes a ndarray • False: Passes a pandas Series
* engine: 'python' or 'numba'
> engine_kwargs, args, kwargs ✅

In [ ]:
import numpy as np
def custom_range(arr):
    return np.max(arr) - np.min(arr)

df4['Rolling_Range'] = df4['Sales'].rolling(window=3).apply(custom_range, raw=True)
df4[['Sales', 'Rolling_Range']]

            Sales  Rolling_Range
Date
2026-01-01    100            NaN
2026-01-02    120            NaN
2026-01-03    110           20.0
2026-01-04    150           40.0
2026-01-05    200           90.0

In [ ]:
def weighted_mean(arr, w1, w2, w3):
    return (arr[0]*w1 + arr[1]*w2 + arr[2]*w3) / (w1 + w2 + w3)

df4['Weighted_Rolling'] = df4['Sales'].rolling(3).apply(weighted_mean, raw=True, args=(1, 2, 3))  # Pass extra weights via args=(w1, w2, w3)
df4[['Sales', 'Weighted_Rolling']]

            Sales  Weighted_Rolling
Date
2026-01-01    100               NaN
2026-01-02    120               NaN
2026-01-03    110        111.666667
2026-01-04    150        131.666667
2026-01-05    200        168.333333

##### DataFrame.expanding(min_periods=1, axis=0, method='single')

* method: 'single' or 'table'

In [ ]:
df4['Cumulative_Sum'] = df4['Sales'].expanding(min_periods=2).sum()
df4[['Sales', 'Cumulative_Sum']]

            Sales  Cumulative_Sum
Date
2026-01-01    100             NaN
2026-01-02    120           220.0
2026-01-03    110           330.0
2026-01-04    150           480.0
2026-01-05    200           680.0

##### DataFrame.ewm(com=None, span=None, halflife=None, alpha=None, min_periods=0, adjust=True, ignore_na=False)

* com: Center of mass ($\alpha = \frac{1}{1 + \text{com}}$).
* span: $N$-period moving average decay ($\alpha = \frac{2}{N + 1}$). Most commonly used.
* halflife: Time for weight to decay by half.
* alpha: Direct smoothing factor ($0 < \alpha \le 1$).
> adjust, ignore_na ✅

In [ ]:
df4['EMA_3'] = df4['Sales'].ewm(span=3).mean()
df4[['Sales', 'EMA_3']]

            Sales       EMA_3
Date
2026-01-01    100  100.000000
2026-01-02    120  113.333333
2026-01-03    110  111.428571
2026-01-04    150  132.000000
2026-01-05    200  167.096774

##### **Row Numbers:** Row numbering assigns a sequential index (0, 1, 2...) to rows.

A. **Global Row Numbers (`reset_index()`):** Resets the index of a DataFrame back to consecutive integers ($0$ to $N-1$) and moves the existing index into a standard column.

DataFrame.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')

* drop: If truee, discards the existing index instead of saving it as a column.
> level, col_level, col_fill ✅

B. **Group-Wise Row Numbers (`cumcount()`):** Counts rows **per group**, starting at `0` for the first row of each group.

DataFrame.groupby().cumcount(ascending=True)

* Adding $+ 1$ shifts counting from 0-based (0, 1, 2) to 1-based (1, 2, 3).

In [ ]:
df4 = pd.DataFrame({'Student':['Alice', 'Bob', 'Charlie', 'David'], 'Department':['CS', 'CS', 'Math', 'Math'], 'Score':[90, 80, np.nan, 70]})
df4['Group_Row_Num'] = df4.groupby('Department').cumcount() + 1
print(df4)

   Student Department  Score  Group_Row_Num
0    Alice         CS   90.0              1
1      Bob         CS   80.0              2
2  Charlie       Math    NaN              1
3    David       Math   70.0              2

##### Data Ranking

Series.rank(axis=0, method='average', numeric_only=False, na_option='keep', ascending=True, pct=False)

* na_option: How missing values are ranked. 'keep', 'top' or 'bottom'
* pct: computes **percentile rank** (values normalized between 0.0 and 1.0)
> numeric_only ✅

In [ ]:
df4['Rank_Default'] = df4['Score'].rank(ascending=False)
df4[['Score', 'Rank_Default']]

   Score  Rank_Default
0   90.0           1.0
1   80.0           2.0
2    NaN           NaN
3   70.0           3.0

In [ ]:
df4['Percentile_Rank'] = df4['Score'].rank(na_option='bottom', pct=True)
df4[['Score', 'Percentile_Rank']]

   Score  Percentile_Rank
0   90.0             0.75
1   80.0             0.50
2    NaN             1.00
3   70.0             0.25

In [ ]:
s = pd.Series([30, 20, 20, 10])
print(s.rank(method='average')) # Equal values get the average of their positions.
print(s.rank(method='min')) # Equal values get the minimum rank position.
print(s.rank(method='max')) # Equal values get the maximum rank position.
print(s.rank(method='first')) # Ranks assigned in order of appearance in the data.
print(s.rank(method='dense')) # Like 'min', but never skips numbers after ties.

0    4.0
1    2.5
2    2.5
3    1.0
dtype: float64
0    4.0
1    2.0
2    2.0
3    1.0
dtype: float64
0    4.0
1    3.0
2    3.0
3    1.0
dtype: float64
0    4.0
1    2.0
2    3.0
3    1.0
dtype: float64
0    3.0
1    2.0
2    2.0
3    1.0
dtype: float64

##### Quantile Binning

`pd.qcut()` discretizes a continuous numeric variable into **equal-sized frequency buckets** (quantiles), ensuring each bucket contains approximately the same number of samples.

pd.qcut(x, q, labels=None, retbins=False, precision=3, duplicates='raise')

* q: Number of quantiles (e.g., 4) or array of quantiles [0, 0.5, 0.9, 1.0].
* duplicates: 'raise' or 'drop'. If bin edges overlap due to duplicate values, 'drop' merges identical bins.
> retbins, precision ✅

In [ ]:
df4['Score_Bucket'] = pd.qcut(df4['Score'].dropna(), q=2)
df4[['Score', 'Score_Bucket']]

   Score    Score_Bucket
0   90.0    (80.0, 90.0]
1   80.0  (69.999, 80.0]
2    NaN             NaN
3   70.0  (69.999, 80.0]

In [ ]:
df4['Score_Bucket'] = pd.qcut(df4['Score'].dropna(), q=[0, 0.4, 0.7, 1], labels=['Low Scorer', 'Middle Scorer', 'High Scorer'])
df4[['Score', 'Score_Bucket']]
# df4['Score'].dropna() passed only the 3 valid numbers ([90.0, 80.0, 70.0]) to qcut(). qcut() calculated the bins for those 3 rows.

   Score   Score_Bucket
0   90.0    High Scorer
1   80.0  Middle Scorer
2    NaN            NaN
3   70.0     Low Scorer

##### Lag & Lead Operations
It allow you to compare a row's current value with past or future rows without changing the DataFrame order.

* Lag (Looking Back): Shifts data downward, bringing previous values into the current row.
* Lead (Looking Ahead): Shifts data upward, bringing future values into the current row.

Series.shift(periods=1, freq=None, axis=0, fill_value=np.nan)

* freq: Shifts the Datetime Index instead of shifting row values.
* fill_value: Value used to replace boundary NaN.

When working with grouped data (groupby), you often need to pick specific positional records per group (e.g., a customer's first purchase).

DataFrame.groupby('group_column').nth(n, dropna=None)
* nth(0) $\rightarrow$ First value in group.
* nth(-1) $\rightarrow$ Last value in group.

* groupby().first(): Returns the first non-null value for each column within each group.
* groupby().last(): Returns the last non-null value for each column within each group.

In [ ]:
df4['Lag_1'] = df4['Score'].shift(-1)
df4['Lead_1'] = df4['Score'].shift(1)
df4[['Score', 'Lag_1', 'Lead_1']]

   Score  Lag_1  Lead_1
0   90.0   80.0     NaN
1   80.0    NaN    90.0
2    NaN   70.0    80.0
3   70.0    NaN     NaN

In [ ]:
df4['nth_first'] = df4.groupby('Department')['Score'].agg('nth', 0) # Should be `transform`
df4['nth_last'] = df4.groupby('Department')['Score'].agg('nth', -1) # Should be `transform`
df4['non_null_first'] = df4.groupby('Department')['Score'].transform('first')
df4['non_null_last'] = df4.groupby('Department')['Score'].transform('last')
df4[['Department', 'Score', 'nth_first', 'nth_last', 'non_null_first', 'non_null_last']]

  Department  Score  nth_first  nth_last  non_null_first  non_null_last
0         CS   90.0       90.0       NaN            90.0           80.0
1         CS   80.0        NaN      80.0            90.0           80.0
2       Math    NaN        NaN       NaN            70.0           70.0
3       Math   70.0        NaN      70.0            70.0           70.0

In [ ]:
df4.groupby('Department')['Score'].agg(['first', 'last'])

            first  last
Department
CS           90.0  80.0
Math         70.0  70.0

##### pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=None, indicator=False, validate=None)

Other Syntax: `df1.merge(df2, ...)`

* on: Column/index **names** to join on. Must exist in both DataFrames.
* left_on: Column/index level names in left DataFrame to join on.
* right_on: Column/index level names in right DataFrame to join on.
* left_index: If True, uses row index of left DataFrame as join key.
* right_index: If True, uses row index of right DataFrame as join key.
* suffixes: String suffix added to overlapping column names not used in join.
* indicator: Adds `_merge` column indicating source of each row (both, left_only, right_only). `bool or str`
> * validate: Checks merge type ('1:1', '1:m', 'm:1', 'm:m'). Raises error if violated.
```
┌────────────┬─────────────┬──────┐
│  left_on   │  right_on   │      │
├────────────┼─────────────┤──────┤
│ left_index │ right_index │      │
├────────────┼─────────────┼──────┤
│            │             │  on  │
└────────────┴─────────────┴──────┘
```

| how= | Description | SQL Equivalent |
| --- | --- | --- |
| **`'inner'`** | Retains only rows with matching keys in **both** DataFrames. | `INNER JOIN` |
| **`'left'`** | Retains all rows from left, filling missing right matches with NaN. | `LEFT OUTER JOIN` |
| **`'right'`** | Retains all rows from right, filling missing left matches with NaN. | `RIGHT OUTER JOIN` |
| **`'outer'`** | Retains all rows from **both** DataFrames, filling gaps with NaN. | `FULL OUTER JOIN` |
| **`'cross'`** | Creates Cartesian product of rows (every left row combined with every right row). | `CROSS JOIN` |

In [ ]:
a = pd.DataFrame({'Student':[101, 102, 103, 104,105], 'Department':['CS', 'CS', 'Math', 'Math', 'CS'], 'Score':[70, 80, 85, 90, 73]})
b = pd.DataFrame({'Sports':['Basketball', 'Football', 'Chess', 'Tennis', 'Football'], 'Department':['CS', 'CS', 'Math', 'Math', 'ECE']}, index=[101, 102, 103, 104, 106])

In [ ]:
pd.merge(a, b, on='Department', how='outer')

    Student Department      Sports
0     101.0         CS  Basketball
1     101.0         CS    Football
2     102.0         CS  Basketball
3     102.0         CS    Football
4     105.0         CS  Basketball
5     105.0         CS    Football
6       NaN        ECE    Football
7     103.0       Math       Chess
8     103.0       Math      Tennis
9     104.0       Math       Chess
10    104.0       Math      Tennis

In [ ]:
pd.merge(a, b, left_on='Department', right_on='Sports', how='outer', suffixes=('_a', '_b'), indicator=True)

   Student Department_a  Score      Sports Department_b      _merge
0      NaN          NaN    NaN  Basketball           CS  right_only
1    101.0           CS   70.0         NaN          NaN   left_only
2    102.0           CS   80.0         NaN          NaN   left_only
3    105.0           CS   73.0         NaN          NaN   left_only
4      NaN          NaN    NaN       Chess         Math  right_only
5      NaN          NaN    NaN    Football           CS  right_only
6      NaN          NaN    NaN    Football          ECE  right_only
7    103.0         Math   85.0         NaN          NaN   left_only
8    104.0         Math   90.0         NaN          NaN   left_only
9      NaN          NaN    NaN      Tennis         Math  right_only

In [ ]:
# a.merge(b, left_on='Department', right_index=True, how='outer')
# You are trying to merge on object and int64 columns for key 'Department'.
a.merge(b, left_on='Score', right_index=True, how='outer')
# When merging using left_on, pandas drops the original row ordering of the left DataFrame and replaces the index with the join key values.
# Since those right-hand rows did not have a matching index value from a, pandas assigned NaN as their row index in the final combined DataFrame. or use `.reset_index()`

     Student Department_x  Score      Sports Department_y
0.0    101.0           CS     70         NaN          NaN
4.0    105.0           CS     73         NaN          NaN
1.0    102.0           CS     80         NaN          NaN
2.0    103.0         Math     85         NaN          NaN
3.0    104.0         Math     90         NaN          NaN
NaN      NaN          NaN    101  Basketball           CS
NaN      NaN          NaN    102    Football           CS
NaN      NaN          NaN    103       Chess         Math
NaN      NaN          NaN    104      Tennis         Math
NaN      NaN          NaN    106    Football          ECE

pd.concat(objs, axis=0, join='outer', ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=False, copy=None)

* join: 'inner' or 'outer'
* keys: Adds a hierarchical MultiIndex to distinguish which source DataFrame came from.
* names: Assign explicit label names to the levels of the resulting MultiIndex when we use the keys parameter.
> levels, verify_integrity ✅

In [ ]:
a = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
b = pd.DataFrame({'A': [7, 8], 'B': [9, 10]})

In [ ]:
pd.concat([a, b], axis=1, join='inner')

   A  B  A   B
0  1  4  7   9
1  2  5  8  10

In [ ]:
pd.concat([a, b], axis=1, keys=['a', 'b'], names=['Keys', 'Index'])

Keys   a       b
Index  A  B    A     B
0      1  4  7.0   9.0
1      2  5  8.0  10.0
2      3  6  NaN   NaN